from pydantic import BaseModel, Field   

class ChatRequest(BaseModel):
    video_url: str = Field(..., description="paste the Youtube URL to be processed")
    question: str = Field(..., description="enter your question related to the video")

class ChatResponse(BaseModel):
    answer: str = Field(..., description="the answer generated by the AI chatbot based on the video content")
    title:str | None = Field(None, description="the title of the YouTube video")
    thumbnail_url: str | None = Field(None, description="the thumbnail URL of the YouTube video")


